test_suites:
    - name: e2e
      script_path: /root/okta/samples-js-react/scripts
      sort_order: '1'
      timeout: '20'
      script_name: e2e
      criteria: MERGE
      queue_name: small

    - name: e2e-oie
      script_path: /root/okta/samples-js-react/scripts
      sort_order: '1'
      timeout: '20'
      script_name: e2e-oie
      criteria: MERGE
      queue_name: small
